//! Deterministic synthetic test images.
//!
//! Everything here is generated procedurally, so fixtures carry no third-party
//! copyright and can be regenerated bit-for-bit. The same scene is available as a
//! Bayer or X-Trans DNG (exercises the RAW path), a JPEG (display-referred path) and a
//! [`LinearImage`] (renderer golden tests, independent of any decoder).

mod dng;
mod scene;
mod tempdir;

use image_core::{LinearImage, color};

pub use dng::{DNG_MAKE, DNG_MODEL, XTRANS_TEXTURE, chart_dng, chart_xtrans_dng};
pub use scene::{chart_neutral_value, chart_probe_neutral, sample};
pub use tempdir::TempDir;

/// The chart as a scene-linear image (no decoder involved).
pub fn chart_linear(width: u32, height: u32) -> LinearImage {
    let mut data = Vec::with_capacity(width as usize * height as usize * 3);
    for y in 0..height {
        for x in 0..width {
            for c in sample(x, y, width, height) {
                data.push((c.clamp(0.0, 1.0) * 65535.0).round() as u16);
            }
        }
    }
    LinearImage::new(width, height, data).expect("chart dimensions are consistent")
}

/// The chart encoded as an sRGB JPEG.
pub fn chart_jpeg(width: u16, height: u16, quality: u8) -> Vec<u8> {
    let (w, h) = (u32::from(width), u32::from(height));
    let mut rgb = Vec::with_capacity(w as usize * h as usize * 3);
    for y in 0..h {
        for x in 0..w {
            for c in sample(x, y, w, h) {
                rgb.push((color::linear_to_srgb(c.clamp(0.0, 1.0)) * 255.0).round() as u8);
            }
        }
    }
    encode_jpeg(&rgb, width, height, quality)
}

/// A single-colour sRGB JPEG.
pub fn solid_jpeg(width: u16, height: u16, rgb: [u8; 3]) -> Vec<u8> {
    let data: Vec<u8> = (0..usize::from(width) * usize::from(height))
        .flat_map(|_| rgb)
        .collect();
    encode_jpeg(&data, width, height, 100)
}

fn encode_jpeg(rgb: &[u8], width: u16, height: u16, quality: u8) -> Vec<u8> {
    let mut out = Vec::new();
    let encoder = jpeg_encoder::Encoder::new(&mut out, quality);
    encoder
        .encode(rgb, width, height, jpeg_encoder::ColorType::Rgb)
        .expect("in-memory JPEG encoding cannot fail for valid dimensions");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(chart_dng(64, 40), chart_dng(64, 40));
        assert_eq!(chart_jpeg(64, 40, 90), chart_jpeg(64, 40, 90));
        assert_eq!(chart_linear(64, 40), chart_linear(64, 40));
    }

    #[test]
    fn committed_fixtures_match_generator() {
        // tests/fixtures/synthetic is generated by `gen-fixtures`; keep them in sync.
        let dir =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/synthetic");
        let dng = std::fs::read(dir.join("chart.dng")).expect("run gen-fixtures");
        let jpg = std::fs::read(dir.join("chart.jpg")).expect("run gen-fixtures");
        assert!(
            dng == chart_dng(1200, 800),
            "chart.dng is stale; run gen-fixtures"
        );
        assert!(
            jpg == chart_jpeg(1200, 800, 92),
            "chart.jpg is stale; run gen-fixtures"
        );
    }

    #[test]
    fn neutral_probe_is_neutral() {
        let (x, y) = chart_probe_neutral(640, 400);
        let px = sample(x, y, 640, 400);
        assert_eq!(px, [chart_neutral_value(); 3]);
    }
}
